# Generated by Django 3.1.1 on 2020-10-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.CharField(max_length=50)),
                ('element', models.CharField(choices=[('NON', 'None'), ('FIR', 'Fire'), ('WAT', 'Water'), ('THN', 'Thunder'), ('DRG', 'Dragon'), ('BLS', 'Blast'), ('PAR', 'Paralysis'), ('PSN', 'Posion'), ('SLP', 'Sleep')], default='NON', max_length=3)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.monster')),
            ],
        ),
    ]
