# Generated by Django 3.1.1 on 2020-10-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201008_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='weaknesses',
            field=models.ManyToManyField(to='main_app.Weakness'),
        ),
    ]
