# Generated by Django 3.1.1 on 2020-10-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_monster_weaknesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attacks',
            name='element',
            field=models.CharField(choices=[('NON', 'None'), ('FIR', 'Fire'), ('WAT', 'Water'), ('ICE', 'Ice'), ('THN', 'Thunder'), ('DRG', 'Dragon'), ('BLS', 'Blast'), ('PAR', 'Paralysis'), ('PSN', 'Posion'), ('SLP', 'Sleep')], default='NON', max_length=3),
        ),
        migrations.AlterField(
            model_name='monster',
            name='element',
            field=models.CharField(max_length=150),
        ),
    ]
